version: "3.9"

services:

  migrate:
    build:
      context: ./backend
    image: webhook-api
    command: alembic upgrade head
    env_file:
      - ./backend/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./backend:/app

  api:
    image: webhook-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  # react-cli-tool:
  #   image: node:20-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   command: "echo 'CLI Tool is ready'"
  #   tty: true

  react-app:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true