version: "3.9"

services:

  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: appdb
  #     POSTGRES_USER: appuser
  #     POSTGRES_PASSWORD: apppassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  migrate:
    build:
      context: ./backend
    image: webhook-api
    command: alembic upgrade head
    env_file:
      - ./backend/.env

  api:
    image: webhook-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

# volumes:
#   pgdata: